export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const ADD_TO_INCOME = "ADD_TO_INCOME";
export const ADD_TO_EXPENSE = "ADD_TO_EXPENSE";
export const ADD_TO_BALANCE = "ADD_TO_BALANCE";
export const EXCHANGE_CURRENCY = "EXCHANGE_CURRENCY";
